# -----------------------------------------------------------
# Formula
# -----------------------------------------------------------
brew 'coreutils'
brew 'fzf'
brew 'sheldon'
brew 'starship'
brew 'gh'
brew 'zsh'
brew 'uv'
brew 'yarn'
brew 'git'

# -----------------------------------------------------------
# Cask
# -----------------------------------------------------------
cask 'google-chrome'
cask 'wezterm'
cask 'cursor'
cask 'docker-desktop'
cask 'visual-studio-code'
cask 'slack'
cask 'zoom'
cask 'notion'
cask '1password'
cask 'claude'
cask 'flux-app'
cask 'wireshark'
