# Powerlevel10k設定ファイル - シンプルな1行表示用

# 基本設定
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

# 1行表示に最適化
typeset -g POWERLEVEL9K_PROMPT_ON_NEWLINE=false
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX=''
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=''
typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=false

# 左側のプロンプト要素
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  # 基本要素
  dir                     # カレントディレクトリ
  vcs                     # git情報
)

# 右側のプロンプト要素
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  status                  # 前のコマンドの終了コード
  command_execution_time  # 直前のコマンドの実行時間
)

# プロンプト文字 - 通常の「%」の代わりに使用
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND=76
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND=196

# ディレクトリ表示のスタイル設定
typeset -g POWERLEVEL9K_DIR_FOREGROUND=39
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=39
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=39
typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=30
typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_last
typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=1

# VCS（Git）の表示設定
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=76
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=178
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=39
typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND=196
typeset -g POWERLEVEL9K_VCS_LOADING_FOREGROUND=244
typeset -g POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_EXPANSION=''

# コマンド実行時間の表示設定
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=1
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=2
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=178

# ステータス表示の設定
typeset -g POWERLEVEL9K_STATUS_OK=false
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=196
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=196

# アイコン設定
typeset -g POWERLEVEL9K_MODE="nerdfont-complete"

# トランケーション設定
typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=".."
typeset -g POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=false

# conda環境表示の設定
typeset -g POWERLEVEL9K_ANACONDA_SHOW_PYTHON_VERSION=false
typeset -g POWERLEVEL9K_ANACONDA_FOREGROUND=37
typeset -g POWERLEVEL9K_ANACONDA_CONTENT_EXPANSION=''

# Python仮想環境表示の設定
typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=37
typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=false
typeset -g POWERLEVEL9K_VIRTUALENV_CONTENT_EXPANSION=''

# ホストマシンを表示しない
typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=232
typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=7
typeset -g POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND=196
typeset -g POWERLEVEL9K_ROOT_INDICATOR_FOREGROUND=232

# Condaの環境表示を無効化
typeset -g POWERLEVEL9K_ANACONDA_SHOW_ON_COMMAND='' 