dbaeumer.vscode-eslint
dgeibi.alias-tool
editorconfig.editorconfig
esbenp.prettier-vscode
github.vscode-pull-request-github
ionutvmi.path-autocomplete
mechatroner.rainbow-csv
ms-azuretools.vscode-docker
ms-ceintl.vscode-language-pack-ja
ms-playwright.playwright
ms-python.debugpy
ms-python.isort
ms-python.python
ms-vsliveshare.vsliveshare
pkief.material-icon-theme
quarto.quarto
redhat.vscode-xml
reditorsupport.r
ritwickdey.liveserver
sibiraj-s.vscode-scss-formatter
streetsidesoftware.code-spell-checker
stylelint.vscode-stylelint
vscode-icons-team.vscode-icons
vue.volar
vue.vscode-typescript-vue-plugin
zhuangtongfa.material-theme
