# Starship設定ファイル - シンプルで1行のプロンプト

# プロンプト全体のフォーマット（一行に統合）
format = "$username$hostname $directory$cmd_duration$character"

# コマンド入力前の空行を非表示
add_newline = false

# プロンプトの文字設定
[character]
success_symbol = " [❯](green)"
error_symbol = " [❯](red)"
vimcmd_symbol = " [❮](green)"

# ディレクトリ表示設定
[directory]
style = "blue"
truncation_length = 3
truncation_symbol = "…/"
read_only = " 🔒"
format = "[$path]($style)"

# Gitブランチ表示設定（無効化）
[git_branch]
disabled = true

# Gitステータス表示設定（無効化）
[git_status]
disabled = true

# コマンド実行時間表示
[cmd_duration]
min_time = 500
format = " [($duration)]($style)"
style = "yellow"

# ホスト名表示
[hostname]
ssh_only = false
format = "[@$hostname]($style)"
style = "green"

# ユーザー名表示
[username]
show_always = true
format = "[$user]($style_user)"
style_user = "blue" 