name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  dotfile-test:
    name: Install test
    timeout-minutes: 60
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dotfiles
        run: CI=true ./setup/setup.zsh
