name: CI

on:
  push:
  schedule:
    - cron: "0 0 1,15 * *"

jobs:
  test:
    name: Install test
    timeout-minutes: 60
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Make scripts executable
        run: |
          find ./setup -name "*.sh" -exec chmod +x {} \;
          find ./setup -name "*.zsh" -exec chmod +x {} \;
          chmod +x ./install.sh
      - name: Install dotfiles
        run: CI=true ./setup/install.sh
