name: Test Dotfiles Setup

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-setup:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zshrc
          eval "$(/opt/homebrew/bin/brew shellenv)"

      - name: Make scripts executable
        run: |
          chmod +x setup/*.sh
          chmod +x setup/install/*.zsh

      - name: Run setup script
        run: |
          cd setup
          FORCE=1 CI=true ./install.sh

      - name: Verify Zsh Configuration
        run: |
          test -f ~/.zshrc && echo "Zsh configuration verified"

      - name: Verify Git Configuration
        run: |
          git config --list | grep -q "user.name" && echo "Git configuration verified"

      - name: Verify VSCode Configuration
        run: |
          test -f ~/Library/Application\ Support/Code/User/settings.json && echo "VSCode configuration verified" || echo "VSCode configuration not found"

      - name: Verify Cursor Configuration
        run: |
          test -f ~/.config/cursor/rules/assistant.mdc && echo "Cursor configuration verified" || echo "Cursor configuration not found"
